### ISSUE TITLE
error coming while trying to run the code

### ISSUE THREAD

**Issue by ashishkishor** [clips/fewshot-biomedical-names#1]
I was trying to run the code with given below arguments on colab---->
!python main.py --fasttext pub2fast.bin --outfile out1.txt --gpu 1
but the error is coming given below----->
Initializing encoder...
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    gpu_index=args.gpu,
  File "/content/drive/MyDrive/fewshot-biomedical-names/encoder.py", line 22, in __init__
    super().__init__(**kwargs)
  File "/content/drive/MyDrive/fewshot-biomedical-names/encoder_base.py", line 138, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'triplet_margin'

while trying to fix this ,i commented out the line 35 in main.py but then error was it was not able to create object for fast text

**Comment by PieterFivez** [comment]
Hi Ashish,

Thanks for your interest in the code! I've added the triplet_margin argument to the Encoder class (it was indeed missing somehow). Please try again with the latest commit.

**Comment by ashishkishor** [comment]
As i told in previous issue, fasttext model is unable to create a object after loading the model that's why it's giving error given below in the colab and in system too ,I attaching collab screenshot for your reference 


**********
Initializing encoder...
Loading fastText model...
Done
  0% 0/71703 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    gpu_index=args.gpu,
  File "/content/drive/My Drive/fewshot-biomedical-names/encoder.py", line 22, in __init__
    super().__init__(**kwargs)
  File "/content/drive/My Drive/fewshot-biomedical-names/encoder_base.py", line 138, in __init__
    super().__init__(**kwargs)
  File "/content/drive/My Drive/fewshot-biomedical-names/encoder_base.py", line 38, in __init__
    self.pretrained_name_embeddings = self.vectorize.create_reach_object(all_names)
  File "/content/drive/My Drive/fewshot-biomedical-names/vectorize.py", line 52, in create_reach_object
    token_embs = self.vectorize_string(name, norm=False)
  File "/content/drive/My Drive/fewshot-biomedical-names/vectorize.py", line 38, in vectorize_string
    vector = self.fasttext_model.get_word_vector(token)
AttributeError: 'NoneType' object has no attribute 'get_word_vector'
********
![error_fewshot](https://user-images.githubusercontent.com/23038611/124081202-dd594080-da68-11eb-89a4-db6fcedf0f47.PNG)

**Comment by PieterFivez** [comment]
I'm sorry, one line was left in which reinitialized the fastText model attribute. I left it out now and everything runs correctly from start to finish for me, this is a screenshot of the output of my terminal:

![fewshot_output](https://user-images.githubusercontent.com/17811776/124399537-57652000-dd1c-11eb-8fd3-112aebf04a81.png)
